# fly.toml app configuration file generated for pokeman-summer-bush-3988 on 2024-11-10T12:10:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pokeman-summer-bush-3988'
primary_region = 'gru'

[experimental]
  cmd = ['mongod', '--ipv6']

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'

[[mounts]]
  source = 'productiondb_storage'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
